name: Pull Request
on:
  pull_request:
    types: [opened, labeled, synchronize, reopened]
jobs:
  RunTests:
    # For public gems, use:
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, linux, x64, bwstaging]
    steps:
      # Setup
      - uses: actions/checkout@v2
      #
      # For public gems, remove the aws-actions/configure-aws-credentials@v1 clause
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          mask-aws-account-id: false
      # ruby/setup-ruby@v1 will use .ruby-version
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      # Test
      - name: Test with rspec
        run: bundle exec rspec
      - name: Run Rubocop
        run: bundle exec rubocop
